# Generated by Django 4.2.3 on 2023-07-31 09:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                (
                    'department',
                    models.CharField(
                        choices=[
                            ('', 'Services '),
                            ('U PVC Windows', 'U PVC Windows'),
                            ('Wood Works', 'Wood Works'),
                            ('Steel Works', 'Steel Works'),
                            ('Painting Works', 'Painting Works'),
                            ('Welding Works', 'Welding Works'),
                            ('For Apartments & Commercial Buildings', 'For Apartments & Commercial Buildings'),
                        ],
                        max_length=50,
                    ),
                ),
                ('number', models.CharField(max_length=10)),
                ('website', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.CharField(max_length=335)),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
