# Generated by Django 4.2.3 on 2023-07-31 11:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [('web', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.CharField(
                choices=[('finance', 'Finance'), ('investment', 'Investment'), ('others', 'Others')], max_length=50
            ),
        )
    ]
