# Generated by Django 4.2.3 on 2023-08-01 06:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [('web', '0003_sector')]

    operations = [
        migrations.RemoveField(model_name='sector', name='user'),
        migrations.AddField(
            model_name='sector',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
