# Generated by Django 4.2.3 on 2023-08-01 07:28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [('web', '0004_remove_sector_user_sector_description')]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='icon_image',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AlterField(model_name='sector', name='image', field=models.ImageField(upload_to='upload')),
    ]
