# Generated by Django 4.2.3 on 2023-08-04 08:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [('web', '0005_sector_icon_image_alter_sector_image')]

    operations = [
        migrations.RemoveField(model_name='sector', name='comment'),
        migrations.AddField(
            model_name='update', name='posted', field=models.CharField(default=1, max_length=10), preserve_default=False
        ),
    ]
