# Generated by Django 4.2.3 on 2023-08-04 09:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [('web', '0006_remove_sector_comment_update_posted')]

    operations = [
        migrations.AddField(
            model_name='update',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        )
    ]
