# Generated by Django 4.2.3 on 2023-08-08 10:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [('web', '0007_update_description')]

    operations = [
        migrations.AlterField(model_name='update', name='description', field=models.CharField(max_length=200)),
        migrations.AlterField(model_name='update', name='summary', field=models.CharField(max_length=500)),
    ]
