# Generated by Django 4.2.3 on 2023-08-11 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('web', '0008_alter_update_description_alter_update_summary')]

    operations = [migrations.RemoveField(model_name='sector', name='icon_image')]
