# Generated by Django 4.2.3 on 2023-08-12 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('web', '0009_remove_sector_icon_image')]

    operations = [
        migrations.RemoveField(model_name='contact', name='last_name'),
        migrations.RemoveField(model_name='contact', name='website'),
    ]
