# Generated by Django 4.2.3 on 2023-08-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0011_alter_contact_department')]

    operations = [
        migrations.AlterField(model_name='sector', name='description', field=models.CharField(max_length=500)),
        migrations.AlterField(model_name='sector', name='summary', field=models.CharField(max_length=505)),
    ]
