# Generated by Django 4.2.3 on 2023-08-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0012_alter_sector_description_alter_sector_summary')]

    operations = [
        migrations.AlterField(model_name='contact', name='message', field=models.TextField()),
        migrations.AlterField(model_name='sector', name='description', field=models.TextField()),
        migrations.AlterField(model_name='sector', name='summary', field=models.TextField()),
        migrations.AlterField(model_name='update', name='description', field=models.TextField()),
        migrations.AlterField(model_name='update', name='summary', field=models.TextField()),
    ]
