# Generated by Django 4.2.3 on 2023-08-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0013_alter_contact_message_alter_sector_description_and_more')]

    operations = [
        migrations.AlterField(model_name='sector', name='summary', field=models.TextField(blank=True, null=True))
    ]
